In [2]:
import pandas as pd
import numpy as np
import os

In [10]:
listImage = os.listdir(os.path.abspath('/data/CellData/train/'))
GTList = pd.read_csv(os.path.abspath('/data/CellData/train.csv'))

In [16]:
print(GTList)

                                         ID  Label
0      5c27f04c-bb99-11e8-b2b9-ac1f6b6435d0  8|5|0
1      5fb643ee-bb99-11e8-b2b9-ac1f6b6435d0   14|0
2      60b57878-bb99-11e8-b2b9-ac1f6b6435d0    6|1
3      5c1a898e-bb99-11e8-b2b9-ac1f6b6435d0  16|10
4      5b931256-bb99-11e8-b2b9-ac1f6b6435d0   14|0
...                                     ...    ...
21801  dd0989c4-bbca-11e8-b2bc-ac1f6b6435d0     14
21802  dd1f7fb8-bbca-11e8-b2bc-ac1f6b6435d0    3|0
21803  dd5cb36a-bbca-11e8-b2bc-ac1f6b6435d0   14|0
21804  df573730-bbca-11e8-b2bc-ac1f6b6435d0     14
21805  dea19dc6-bbca-11e8-b2bc-ac1f6b6435d0    5|0

[21806 rows x 2 columns]


In [18]:
def oneHotEncoding(label):
    OH = np.zeros(19)
    for con in label:
        OH[con] = 1
    return OH

In [20]:
N = len(GTList)

oneHotEmbedding = []
for i in range(N):
    labels = GTList['Label'][i]
    labels = labels.split('|')
    labels = [ int(x) for x in labels ]
    labels = oneHotEncoding(labels)
    oneHotEmbedding.append(labels)
oneHotEmbedding = np.array(oneHotEmbedding)
print(oneHotEmbedding)
print(oneHotEmbedding.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
(21806, 19)


In [22]:
from PIL import Image

imageType = ['red', 'green', 'blue', 'yellow']
ImagePath = os.path.abspath('/data/CellData/train')

def imageMerge(imageHash):
    imageList = []
    for i in range(4):
        imageName = imageHash + '_' + imagType[i] + '.png'
        imageArray = Image.open(ImagePath + '/' + imageName, cv2.IMREAD_UNCHANGED)
        imageList.append(imageArray)
    RGBYImage = np.transpose(np.array(imageList), (1, 2, 0))
    return RGBYImage

In [14]:
N = len(GTList)

image2Train = []
for i in range(N):
    imageHash = GTList['ID'][i]
    image2Load = imageMerge(imageHash)
    image2Train.append(image2Load)
imageArr2Load = np.array(image2Train)
print(imageArr2Load.shape)

21806
