In [2]:
import pandas as pd
import numpy as np
import os

In [10]:
listImage = os.listdir(os.path.abspath('/data/CellData/train/'))
GTList = pd.read_csv(os.path.abspath('/data/CellData/train.csv'))

In [16]:
print(GTList)

                                         ID  Label
0      5c27f04c-bb99-11e8-b2b9-ac1f6b6435d0  8|5|0
1      5fb643ee-bb99-11e8-b2b9-ac1f6b6435d0   14|0
2      60b57878-bb99-11e8-b2b9-ac1f6b6435d0    6|1
3      5c1a898e-bb99-11e8-b2b9-ac1f6b6435d0  16|10
4      5b931256-bb99-11e8-b2b9-ac1f6b6435d0   14|0
...                                     ...    ...
21801  dd0989c4-bbca-11e8-b2bc-ac1f6b6435d0     14
21802  dd1f7fb8-bbca-11e8-b2bc-ac1f6b6435d0    3|0
21803  dd5cb36a-bbca-11e8-b2bc-ac1f6b6435d0   14|0
21804  df573730-bbca-11e8-b2bc-ac1f6b6435d0     14
21805  dea19dc6-bbca-11e8-b2bc-ac1f6b6435d0    5|0

[21806 rows x 2 columns]


In [18]:
def oneHotEncoding(label):
    OH = np.zeros(19)
    for con in label:
        OH[con] = 1
    return OH

In [20]:
N = len(GTList)

oneHotEmbedding = []
for i in range(N):
    labels = GTList['Label'][i]
    labels = labels.split('|')
    labels = [ int(x) for x in labels ]
    labels = oneHotEncoding(labels)
    oneHotEmbedding.append(labels)
oneHotEmbedding = np.array(oneHotEmbedding)
print(oneHotEmbedding)
print(oneHotEmbedding.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
(21806, 19)


In [22]:
from PIL import Image

imageType = ['red', 'green', 'blue', 'yellow']
ImagePath = os.path.abspath('/data/CellData/train')

def imageMerge(imageHash):
    imageList = []
    for i in range(4):
        imageName = imageHash + '_' + imagType[i] + '.png'
        imageArray = Image.open(ImagePath + '/' + imageName, cv2.IMREAD_UNCHANGED)
        imageList.append(imageArray)
    RGBYImage = np.transpose(np.array(imageList), (1, 2, 0))
    return RGBYImage

In [14]:
N = len(GTList)

image2Train = []
for i in range(N):
    imageHash = GTList['ID'][i]
    image2Load = imageMerge(imageHash)
    image2Train.append(image2Load)
imageArr2Load = np.array(image2Train)
print(imageArr2Load.shape)

21806


In [2]:
import os
testList = os.listdir(os.path.abspath('/data/CellData/test'))

['131ee8b4-de1d-435f-843c-a907dfda8416_blue.png', '1f4a5c57-54ee-4679-bbc0-cb1c668c3bf7_red.png', 'ecc4e760-3e4d-4117-9341-d5a3dfa35e48_red.png', '2108ef53-d3ae-4438-9dab-2cc5696a286b_blue.png', 'c2f10f94-1351-42d8-ba4d-428ac5f21211_blue.png', '283ecafc-ef2b-42f0-a6e1-88129a4fbdd7_red.png', '66382cfa-8da3-49e1-a57b-61ef7794f23f_blue.png', 'c6379d83-6b05-4a29-8f56-05a381d94d2a_blue.png', '3b44694a-9be6-4b9f-9f5f-1dc6c95fff2e_red.png', 'ecd81467-e191-4b3a-9df6-504ad1102990_blue.png', '4e3ae702-1b3c-4eff-b27d-bac809f39c3a_blue.png', '89754d37-1d55-4e5a-9e33-bde4148c0c4b_green.png', '9b1d4b27-6946-4b86-a818-8e91029c3dfa_red.png', '2f6838aa-37d6-41c9-a66a-d047330e0fbf_yellow.png', '02861579-97fb-4482-a613-356e0bf5d090_green.png', '6fb09267-c6ae-4472-896e-b922870ba7e0_blue.png', 'b6fac394-325f-4c94-9e9e-8d568f227089_blue.png', '1425e575-3e6e-4fc4-a7be-d446b543553b_green.png', 'fd13438a-437b-49c0-8301-52c37fd8694f_yellow.png', '41d66623-0e0b-466e-bda4-3acd5ca3158f_yellow.png', '690bd266-6160-

In [9]:
N = len(testList)

imageType = ['red', 'green', 'blue', 'yellow']

imageDict = {}
for i in range(N):
    imageHash = testList[i].split('_')[0]
    try:
        imageDict[imageHash].append(testList[i])
    except:
        imageDict[imageHash] = [testList[i]]

for i, key in enumerate(imageDict):
    print(key)

131ee8b4-de1d-435f-843c-a907dfda8416
1f4a5c57-54ee-4679-bbc0-cb1c668c3bf7
ecc4e760-3e4d-4117-9341-d5a3dfa35e48
2108ef53-d3ae-4438-9dab-2cc5696a286b
c2f10f94-1351-42d8-ba4d-428ac5f21211
283ecafc-ef2b-42f0-a6e1-88129a4fbdd7
66382cfa-8da3-49e1-a57b-61ef7794f23f
c6379d83-6b05-4a29-8f56-05a381d94d2a
3b44694a-9be6-4b9f-9f5f-1dc6c95fff2e
ecd81467-e191-4b3a-9df6-504ad1102990
4e3ae702-1b3c-4eff-b27d-bac809f39c3a
89754d37-1d55-4e5a-9e33-bde4148c0c4b
9b1d4b27-6946-4b86-a818-8e91029c3dfa
2f6838aa-37d6-41c9-a66a-d047330e0fbf
02861579-97fb-4482-a613-356e0bf5d090
6fb09267-c6ae-4472-896e-b922870ba7e0
b6fac394-325f-4c94-9e9e-8d568f227089
1425e575-3e6e-4fc4-a7be-d446b543553b
fd13438a-437b-49c0-8301-52c37fd8694f
41d66623-0e0b-466e-bda4-3acd5ca3158f
690bd266-6160-4909-99d4-e64ca2e6980e
7cde5902-bab9-4245-b4b0-7cf04e1875be
e50129f9-7d45-4997-a179-923f5b12f86b
0cefc8d5-7ded-4de4-ba97-11b0b4a080b0
e8f6cd1e-848a-49c8-a5a1-9231a0b4f4ef
1e4a3df2-c137-437b-9eb3-d3ddc6d7beb6
5eedf48e-cee2-4df8-a934-c39a16f77255
7